FROM --platform=linux/amd64 ubuntu:24.04 AS vlayer-builder
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates dumb-init

WORKDIR /root

RUN curl -L https://vlayer-releases.s3.eu-north-1.amazonaws.com/latest/nightly-linux-amd64.tar.gz -o nightly-linux-amd64.tar.gz
RUN tar -xvf nightly-linux-amd64.tar.gz
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/root/bin/dns_server"]
